#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s1):
    s=''
    if(s1[0].isalpha()):
        s=s+s1[0].upper()
    elif(s1[0].isdigit()):
        s=s+s1[0]
    for i in range(1,len(s1)):
        if(s1[i-1]==' ' and s1[i]!=' '):
            s=s+s1[i].upper()
        else:
            s=s+s1[i]
    return s
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
